name: Go

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        ceph-release:
          - squid
          - tentacle

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Add Ceph repository
        run: |
          curl -fsSL https://download.ceph.com/keys/release.asc | sudo gpg --dearmor -o /usr/share/keyrings/ceph-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/ceph-archive-keyring.gpg] https://download.ceph.com/debian-${{ matrix.ceph-release }}/ jammy main" | sudo tee /etc/apt/sources.list.d/ceph.list

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            ceph \
            ceph-mgr-dashboard \
            python3-setuptools \
            radosgw

      # FIXME
      # https://tracker.ceph.com/issues/74199
      - name: Disable ceph-mgr dashboard smb module
        run: |
          sudo rm -f /usr/share/ceph/mgr/dashboard/controllers/smb.py

      - name: Print Ceph version
        run: ceph --version

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26.3"

      - name: Download go modules
        run: |
          go mod download

      - name: Build
        run: |
          go build

      - name: Tests
        timeout-minutes: 61
        run: |
          go test -timeout 1h
        env:
          TF_ACC: "1"
